spring.application.name=teplapi
# ?????
server.port=8080

jasypt.encryptor.password=@wsx$rfv^yhn
jasypt.encryptor.algorithm=PBEWithMD5AndDES
jasypt.encryptor.iv-generator-classname=org.jasypt.iv.NoIvGenerator

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.url=/v3/api-docs
springdoc.swagger-ui.disable-swagger-default-url=true

# OpenAPI??
validation.custom-annotations.enabled=true

# NXS??
# NXS Logging Configuration
nxs.logging.api.enabled=true
nxs.logging.api.write-to-mq=true
nxs.logging.api.async-mq=true
nxs.logging.api.queue-name=api-log-queue
nxs.logging.api.exchange-name=api-log-exchange
nxs.logging.api.routing-key=api.log

nxs.transaction.prefix="TXN_NXS"
nxs.transaction.date-format: "yyyyMMdd'T'HHmmss"
nxs.transaction.sequence-length: 6

#sql server
primary.datasource.url=${primary.datasource.url:jdbc:sqlserver://tslwsqldb01u.taishinlife.tsh.com.tw;databaseName=TEPL;trustServerCertificate=true}
primary.datasource.dbusername=${primary.datasource.dbusername:TEPLUAT}
primary.datasource.password=${primary.datasource.password:ENC(xPo7r/3obWbyZza+/iY1m0Y07FWo9cq+)}
primary.datasource.driver-class-name=${primary.datasource.driver-class-name:com.microsoft.sqlserver.jdbc.SQLServerDriver}